Tensor Aggregation  
the process of combining multiple elements of a tensor into a single summary value
- Mean
- Min/Max
- Absolute Value
- Sum
- STD/Variance

In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [20]:
tf.random.set_seed(42)
D = tf.random.uniform(shape=[50])
D

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [21]:
# Get Absolute Values
tf.abs(D)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [22]:
# Get The Maximum/Minimum Values
tf.reduce_max(D), tf.reduce_min(D)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [27]:
# Positional Maximum/Minimum
# Refer to the indices or positions of the maximum and minimum values in a tensor. 
# Instead of returning the actual maximum and minimum values, 
# these operations provide the positions or indices at which these extreme values occur.
D[tf.argmax(D)], tf.argmax(D), D[tf.argmin(D)], tf.argmin(D)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [23]:
# Get Summation
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=float32, numpy=25.690401>

In [24]:
# Get Mean
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=float32, numpy=0.513808>

In [25]:
# Get Standard Deviation
# Get Variance
tf.math.reduce_variance(D), tf.math.reduce_std(D)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.070982546>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.2664255>)