# Tensor Operations
- basic operations
- matrix multiplication
- dot product

In [2]:
import tensorflow as tf
print(tf.__version__)

2.13.0


Basic Operations

In [2]:
# You can add values to a tensor using addition, subtraction, multiplication, and division.
tensor = tf.constant([[1, 2],
                     [4, 5]])
tensor * 10
tf.multiply(tensor, 10) # tensor * 10 but faster on gpu uses

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [40, 50]])>

Matrix Multiplication
Rules:
- Inner Dimensions must match
    - mx**n** * **n**xm
- Results matrix has the shape of the outer dims
    - **m**xn * nx**p** = **m**x**p**

In [10]:
# Matrix multiplicaiton in tensorflow is done using tf.matmul
# Rule: inner shapes gotta match ex: 2x3 3x2, 1x5 5x12, etc
tensor @ tensor
# or
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 12],
       [24, 33]])>

In [4]:
# Trans operations to match matrices for multiplication
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[7, 8], [9, 10], [11, 12]])
# Reshape the tensor
# Changes the shape of a tensor while preserving the order of its elements
print("Reshape: ", tf.matmul(X, tf.reshape(Y, [2, 3])))
# Transpose the tensor
# Swaps the rows and columns of a matrix or changes the order of axes in a higher-dimensional tensor
print("Transpose: ", tf.matmul(X, tf.transpose(Y)))

Reshape:  tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)
Transpose:  tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)


In [10]:
# You can also specify the change of the shape using reshape()
tf.matmul(tf.reshape(X, [2, 3]), Y), tf.matmul(X, tf.reshape(Y, [2, 3]))

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])>)

Dot Product (Scalar Product)
- dot product measures the similarity or alignment between two vectors
- A[0]*B[0] + A[1]*B[1] + ... + A[n-1]*B[n-1]

In [4]:
# Perform Dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [6]:
# Change from int32 to int 16
tf.cast(X, dtype=tf.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

Squring, Log, Squre Root

In [7]:
Z = tf.range(1, 10)
Z

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [8]:
# Square it
tf.square(Z)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [12]:
# Square Root
tf.sqrt(tf.cast(Z, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [14]:
# Log
tf.math.log(tf.cast(Z, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## Tensors and NumPy

In [15]:
# Create a tensor direcly from numpy array
import numpy as np
N = tf.constant(np.array([1., 2., 3., 4., 5.]))
N

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 4., 5.])>

In [17]:
# Convert the tensor to a numpy array
np.array(N)
# or
N.numpy()

array([1., 2., 3., 4., 5.])

In [18]:
# Default types are slightly different
np_N = tf.constant(np.array([1., 2., 3., 4., 5.]))
tf_N = tf.constant([1., 2., 3., 4., 5.])

np_N.dtype, tf_N.dtype

(tf.float64, tf.float32)