### One Hot Encoding
Numerical Encoding

In [1]:
import tensorflow as tf

In [2]:
# Create a list of indices
some_list = [0, 1, 2, 3] # red, green, blue, purple

# One hot encode the indices list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [4]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value=True, off_value=False, axis=-1)

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])>