## Creating Random Tensors
### Use Cases
Initializing neural networks for updating representation outputs

In [3]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [8]:
# Create 2 random tensors
# Normal or uniorm randoms Outputs values from a normal or uniformed distribution
a = tf.random.Generator.from_seed(42)
a = tf.random.normal([3, 2])
b = tf.random.Generator.from_seed(42)
b = tf.random.uniform([3, 2])
print("Normal Distribution:", a)
print("Uniform Distribution:", b)

Normal Distribution: tf.Tensor(
[[-1.6226072   1.1364384 ]
 [-0.56687176 -0.7465889 ]
 [ 0.45372462 -0.79342604]], shape=(3, 2), dtype=float32)
Uniform Distribution: tf.Tensor(
[[0.26702178 0.13492346]
 [0.03737497 0.8165958 ]
 [0.815588   0.68314147]], shape=(3, 2), dtype=float32)


### Shuffle a tensor
#### Use cases: 
randomly shuffling a dataset, shuffling a tensor, shuffling a dataset.
this can help models be more acurate for multi classification datasets. Essentially a structured order in datasets can affect learning outcomes 

#### Note
If you want the tensors to be shuffled in the same order you have to use the global level random seed as well as the operation level random seed. 

To make reproducable experiments you want to:
- shuffle your data in a similar order
- initialize with a similar random pattern

In [13]:

not_shuffled = tf.constant([[10, 7], [3, 2], [4, 5]])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 4,  5]])>

In [18]:
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [10,  7],
       [ 4,  5]])>

### Other Ways to make tensors

In [19]:
# create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
# create a tensor of all zeros
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [21]:
# Can turn numpy arrays into tensors
#  the main difference between NumPy Arrays and TensorFlow
# tensors can be run on a GPU faster than NumPy arrays
import numpy as np
numpy_array = np.arange(1, 25, dtype=np.int32)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
# Anything in numpy can be converted to a tf constant tensor
A = tf.constant(numpy_array, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>