### Tensor Attributes
| Attributes | Meaning | Code |
|:----------:|:-------:|:----:|
| Shape | The length (# of elements) of each of the dimenasions of a tensor | tensor.shape |
| Rank | the # of tensor dimensions. A scalar has rank 0, a vector rank 1, a matrix rank2, a tensor rank n. | tensor.ndim |
| Axis | a particular dimension of a tensor | tensor[0], tensor[:, 1], etc... |
| Size | the total number of items in the tensor | tf.size(tensor) | 

In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
# Create rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [6]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor).numpy()

(TensorShape([2, 3, 4, 5]), 4, 120)

In [13]:
# Get first two elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [16]:
# Add in an extra dimension to a tenosr
rank_5_tensor = rank_4_tensor[..., tf.newaxis]
# or 
tf.expand_dims(rank_4_tensor, axis=-1) # expand final axis

rank_5_tensor.ndim

5