In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


Basic Operations

In [9]:
# You can add values to a tensor using addition, subtraction, multiplication, and division.
tensor = tf.constant([[1, 2],
                     [4, 5]])
tensor * 10
tf.multiply(tensor, 10) # tensor * 10 but faster on gpu uses

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [40, 50]])>

Matrix Multiplication

In [10]:
# Matrix multiplicaiton in tensorflow is done using tf.matmul
# Rule: inner shapes gotta match ex: 2x3 3x2, 1x5 5x12, etc
tensor @ tensor
# or
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 12],
       [24, 33]])>