Fundamental concepts of tensorflow

- Introduction to tensors
- Getting information from tensors
- manipulating tensors
- Tenosrs & NumPy
- Using tf.function (speed up regular python functions)
- Using GPUS with TensorFlow (TPU's)

In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
# Create Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check number of dimension of a tensor (ndim)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([1, 2, 3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [5]:
# Check the dims of a vector
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [7]:
# Check the dims of a matrix
matrix.ndim

2

In [11]:
# Create another matrix
another_matrix = tf.constant([[5., 6.], [7., 8.], [1., 3.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[5., 6.],
       [7., 8.],
       [1., 3.]], dtype=float16)>

In [12]:
# Check the dims of a matrix
another_matrix.ndim

2

In [15]:
# Create a tensor
tensor = tf.constant([[[1, 2, 1], [3, 4, 1]], [[5, 6, 1], [7, 8, 1]], [[5, 6, 1], [7, 8, 1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 1],
        [3, 4, 1]],

       [[5, 6, 1],
        [7, 8, 1]],

       [[5, 6, 1],
        [7, 8, 1]]])>

In [14]:
# Check the dims of a tensor
tensor.ndim

3

- Scalar: Single Number
- Vector: A Number with direction (array)
- Matrix a 2 dim array of numbers
- Tensor: n dim array